# docker-compose.server.yml
services:
  db:
    image: postgres:latest
    container_name: ainews_db
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"  # 字符集
    command:
      - postgres
      - -c
      - shared_buffers=32MB        # 内存优化
      - -c
      - max_connections=50
      - -c
      - timezone=Asia/Shanghai
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - internal-net
    restart: unless-stopped
    # 内存限制
    deploy:
      resources:
        limits:
          memory: 100M
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: ainews_redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - internal-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: acdb24/ainewsback:v1.0.1
    container_name: ainews_backend
    env_file: .env
    environment:
      TZ: "Asia/Shanghai"
      HOST: "0.0.0.0"
      PORT: "${PORT:-8080}"
      DB_SERVER: db
      DB_PORT: 5432
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal-net
      - npm-proxy-net
    restart: unless-stopped

volumes:
  db_data:
  redis_data:

networks:
  internal-net:
    name: "ai-news-internal-net"
    driver: bridge
  npm-proxy-net:
    external: true
    name: "npm-proxy-net"